# Generated by Django 2.2.6 on 2019-10-13 09:45

from django.db import migrations, models
import wui.models


class Migration(migrations.Migration):

    dependencies = [
        ('wui', '0003_auto_20191013_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='metisimage',
            name='image_with_bboxes_file',
            field=models.ImageField(null=True, upload_to=wui.models.get_metis_image_display_upload_path),
        ),
    ]
