# Generated by Django 2.2.6 on 2019-10-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wui', '0004_metisimage_image_with_bboxes_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metisimage',
            old_name='image_with_bboxes_file',
            new_name='image_display_file',
        ),
    ]
