version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./metis.nginx:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    env_file:
      - .env.nginx
    ports:
      - "127.0.0.1:8805:80"
  django:
    build: .
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -w 2 -b 0.0.0.0:8000 Metis.wsgi
    volumes:
      - .:/code
    env_file:
      - .env.django
    depends_on:
      - db
  db:
    image: mariadb
    # image: jsurf/rpi-mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env.mysql
