# Generated by Django 2.2.6 on 2019-10-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetisImageAnnotationBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wui.MetisImage')),
                ('tags', models.ManyToManyField(to='wui.MetisObjectTag')),
            ],
        ),
        migrations.DeleteModel(
            name='MetisImageBoundingBox',
        ),
    ]
