# Generated by Django 2.2.6 on 2019-10-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wui', '0002_auto_20191013_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metisimageannotationboundingbox',
            old_name='x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='metisimageannotationboundingbox',
            old_name='y',
            new_name='top',
        ),
        migrations.AlterField(
            model_name='metisimageannotationboundingbox',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bboxes', to='wui.MetisImage'),
        ),
    ]
